### ISSUE TITLE
computeHomo

### ISSUE THREAD

**Issue by manb911** [SherryJYC/3D-Tracking-MVS#5]
Hi, could you enlighten me on what kind/format of 3d co-ordinates is the system expecting and how many do you require?

**Comment by SherryJYC** [comment]
Hi, 
for 3d coordinates, we define (x, y, z) on the football pitch, where z is always 0 as we assume players move on the plane only. For the specific definition of the coordinate system on the pitch, you can check [this file](https://github.com/SherryJYC/3D-Tracking-MVS/blob/main/src/calib.py#L26) to see the definition.
