### ISSUE TITLE
Google Colab Link

### ISSUE THREAD

**Issue by manb911** [SherryJYC/3D-Tracking-MVS#6]
Hi, sorry to bother, but would you be able to provide the google colab link again since the old one seems to have expired

**Comment by JIAOYIING** [comment]
Hi, sorry that the detector's link is currently not available. Please refer to https://colab.research.google.com/drive/1_arNo-81SnqfbdtAhb3TBSU5H0JXQ0_1 (from "Tracking without bells and whistles", https://arxiv.org/abs/1903.05625). You could use this pipeline to fine-tune the detector on your dataset. Thanks for raising this issue.

**Comment by manb911** [comment]
Much appreciated! will look in to it. Thank you !
